export const employeeData = [
  {
    name: "John Doe",
    username: "samarthsb4real",
    designation: "Senior Software Developer",
    email: "yashkolekar1234@gmail.com",
    issuesClosed: 5,
    commits: 15,
    budget: {
      CTC: 250000,
      taxes: 20000,
      trainingCost: 20000,
      additionalCertificationCost: 10000,
    },
  },
  {
    name: "Albert King",
    username: "WhyAsh5114",
    designation: "Cloud Architect",
    email: "anonjr192@gmail.com",
    issuesClosed: 5,
    commits: 25,
    budget: {
      CTC: "250000",
      taxes: "25000",
      trainingCost: "25000",
      additionalCertificationCost: "15000",
      inHand: 200000,
    },
  },
  {
    name: "Jessica Jones",
    username: "sundaram123krishnan",
    designation: "System Administrator",
    email: "anonjr511@gmail.com",
    issuesClosed: 7,
    commits: 22,
    budget: {
      CTC: 180000,
      taxes: 18000,
      trainingCost: 15000,
      additionalCertificationCost: 8000,
      inHand: 85000,
    },
  },
  {
    name: "Jashan Elizabeth",
    username: "GodBoii",
    designation: "Junior Developer",
    email: "myfit.auth@gmail.com",
    issuesClosed: 2,
    commits: 12,
    budget: {
      CTC: 120000,
      taxes: 12000,
      trainingCost: 10000,
      additionalCertificationCost: 5000,
      inHand: 60000,
    },
  },
  {
    name: "Shayla Nico",
    username: "lowercasexyz",
    designation: "Senior Software Developer",
    email: "whyashplaysdota@gmail.com",
    issuesClosed: 3,
    commits: 52,
    budget: {
      CTC: 220000,
      taxes: 22000,
      trainingCost: 20000,
      additionalCertificationCost: 12000,
      inHand: 120000,
    },
  },
  {
    name: "Ray Liotta",
    username: "Kushhhh-sh",
    designation: "Database Administrator",
    email: "krishnsundaram@gmail.com",
    issuesClosed: 9,
    commits: 18,
    budget: {
      CTC: 160000,
      taxes: 16000,
      trainingCost: 15000,
      additionalCertificationCost: 7000,
      inHand: 55000,
    },
  },
];
